version: '3.3'

services:
  postgres:
    hostname: postgres
    image: postgres:14.1
    ports:
      - "51946:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: vkBot
    networks:
      - vkBot_network
  selenium:
    hostname: selenium
    image: selenium/standalone-chrome
    ports:
      - "4444:4444"
    privileged: true
    shm_size: 2g
    networks:
      - vkBot_network
  vk-bot:
    depends_on:
      - postgres
    hostname: vk-bot
    build:
      context: ./
    ports:
      - "5177:80"
    networks:
      - vkBot_network
    env_file:
      - .env

networks:
  vkBot_network: